//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Animals')
export class AnimalsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  type: string;

  @Column('integer', { nullable: true })
  health: number;

  @Column('integer', { nullable: true })
  speed: number;

  @Column('integer', { nullable: true })
  damage: number;
}
