//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Stages')
export class StagesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  stageNumber: number;

  @Column('text', { nullable: true })
  difficultyLevel: string;

  @Column('text', { nullable: true })
  environment: string;

  @Column('text', { nullable: true })
  objectives: string;
}
