//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Weapons')
export class WeaponsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('integer', { nullable: true })
  damage: number;

  @Column('integer', { nullable: true })
  range: number;

  @Column('integer', { nullable: true })
  ammoCount: number;
}
