//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { CarsList, CarsCreate, CarsEdit } from './resources/Cars';
import { WeaponsList, WeaponsCreate, WeaponsEdit } from './resources/Weapons';
import { AnimalsList, AnimalsCreate, AnimalsEdit } from './resources/Animals';
import { StagesList, StagesCreate, StagesEdit } from './resources/Stages';
import CarsIcon from '@mui/icons-material/DriveEta';
import WeaponsIcon from '@mui/icons-material/SportsEsports';
import AnimalsIcon from '@mui/icons-material/Pets';
import StagesIcon from '@mui/icons-material/FilterHdr';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/af9499355">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Cars"
          options={{ label: 'Cars' }}
          list={CarsList}
          create={CarsCreate}
          edit={CarsEdit}
          recordRepresentation="model"
          icon={CarsIcon}
        />
        <Resource
          name="Weapons"
          options={{ label: 'Weapons' }}
          list={WeaponsList}
          create={WeaponsCreate}
          edit={WeaponsEdit}
          recordRepresentation="name"
          icon={WeaponsIcon}
        />
        <Resource
          name="Animals"
          options={{ label: 'Animals' }}
          list={AnimalsList}
          create={AnimalsCreate}
          edit={AnimalsEdit}
          recordRepresentation="type"
          icon={AnimalsIcon}
        />
        <Resource
          name="Stages"
          options={{ label: 'Stages' }}
          list={StagesList}
          create={StagesCreate}
          edit={StagesEdit}
          recordRepresentation="stageNumber"
          icon={StagesIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
